source 'https://rubygems.org'

gem 'private_pub', git: 'https://github.com/he9lin/private_pub.git', ref: '67807876b24'
gem 'thin'
gem 'faye-redis'
gem 'redis-namespace'
gem 'faye', '1.1.1'
gem 'faye_tracking', git: 'https://github.com/he9lin/faye_tracking.git', ref: 'd273e6bd538'
gem 'resque'
gem 'rake'
